fal-ai/dbt-fal

- poetry.lock
- pyproject.toml
- Fixes the `faldbt not found` error
> Fix build and install

- src/fal/cli.py
- src/fal/dag.py
- src/fal/run_scripts.py
- src/faldbt/lib.py
- src/faldbt/parse.py
- src/faldbt/project.py
- tests/test_dag.py
Also added a forgotten argument of profiles_dir and of write_to_firestore
> Organize argument, classes and script running

- src/faldbt/lib.py
This fixes the errors seen in https://github.com/fal-ai/fal/commit/b8dcd21491fa9abf2b7c1a5b97c86d7b3eaf9914 [checks](https://github.com/fal-ai/fal/runs/4917429134?check_suite_focus=true)
> Handle breaking change introduced in pandas 1.4

- docs/sentiment-analysis.md
Working through the sentiment analysis example, I added a few details that will make it simpler for others to complete.
> Update sentiment analysis example

- .github/workflows/pytest.yml
- .gitignore
- README.md
- tests/docker-compose.yml
- tests/mock/.gitignore
- tests/mock/dbt_project.yml
- tests/mock/mockProfile/profiles.yml
- tests/mock/mockTarget/run_results.json
- tests/mock/models/schema.yml
- tests/test_import.py
#128 made us realize that secrets are not available to use for forks of the repo, so we are making tests completely local.
We were not doing any real modifications or reads in GCP before, we were was just connecting to it.
> Migrate to local db tests

- src/faldbt/lib.py
Hey there, 
I'm opening this PR to fix the issue: https://github.com/fal-ai/fal/issues/119
I have already talked to @chamini2 .
Best, Cesar Santos.
*****
closes #119
> Issue-119 - Removing unnecessary logger.info in lib.py

- src/faldbt/project.py
> Fix test node without metadata error

- src/faldbt/lib.py
> Escape jinja braces in row string in write_to_source

- docsite/docs/cli/getting-started.md
- docsite/docusaurus.config.js
- Fix links to edit
- Fix link to functions page
- Fix minor typos
> Minor adjustments to docs

- integration_tests/mock/fal_scripts/my_util.py
- integration_tests/mock/fal_scripts/test.py
- src/fal/cli/fal_runner.py
- src/fal/fal_script.py
> Enable relative imports in fal scripts

- src/fal/cli/cli.py
- src/fal/telemetry/telemetry.py
This just ensures all messages are sent, the fix for SSLSocket warnings is in #202
> Shutdown telemetry by hand to ensure all messages are sent

- integration_tests/features/flow_run.feature
- integration_tests/features/steps/fal_steps.py
- integration_tests/projects/001_flow_run_with_selectors/dbt_project.yml
- src/fal/cli/args.py
- src/fal/cli/dbt_runner.py
- src/fal/cli/fal_runner.py
- src/faldbt/project.py
Makes a state selector work with passed state.
```
fal flow run --select state:new --state my_state_dir --threads 1
```
> Handle dbt state in fal flow run

- src/fal/cli/args.py
- src/fal/cli/dbt_runner.py
- tests/test_cli.py
Makes a `--defer` work.
```
fal flow run --defer --state my_state_dir
```
> Handle dbt defer flag

- integration_tests/features/flow_run.feature
- integration_tests/features/steps/fal_steps.py
- integration_tests/projects/003_scripts_with_errors/dbt_project.yml
- integration_tests/projects/003_scripts_with_errors/fal_scripts/after.py
- integration_tests/projects/003_scripts_with_errors/fal_scripts/before.py
- integration_tests/projects/003_scripts_with_errors/models/schema.yml
- integration_tests/projects/003_scripts_with_errors/models/some_model.sql
- integration_tests/projects/003_scripts_with_errors/profiles.yml
- src/fal/cli/dbt_runner.py
- src/fal/cli/fal_runner.py
- src/fal/cli/flow_runner.py
- src/fal/fal_script.py
- src/fal/run_scripts.py
- tests/test_cli.py
> Stop running when a user scripts fails

- src/faldbt/lib.py
- src/faldbt/project.py
This is not the ideal solution for me; I want to keep it all in a single transaction. To achieve that, maybe I will get better transaction handling in general. I think it's worth exploring. Either way: this is a work in progress.
> Make write_to_source overwrite mode handle errors or cancels better

- integration_tests/features/steps/fal_steps.py
- integration_tests/profiles/bigquery/profiles.yml
- integration_tests/profiles/redshift/profiles.yml
- integration_tests/profiles/snowflake/profiles.yml
let's you run `behave -D profile=bigquery`
allowed profiles are `bigquery`, `redshift` and `snowflake`.
> Integration test with different profiles

- src/faldbt/lib.py
When the table to write to does not exist yet in BigQuery it fails with a 404 error (it should have done `DROP TABLE x IF EXISTS`, but they did not implement `IF EXISTS` part.)
> Fix overwrite mode for bigquery

- .github/workflows/test_profiles.yml
- integration_tests/features/flow_run.feature
- integration_tests/features/run_with_custom_target.feature
- integration_tests/features/steps/fal_steps.py
- integration_tests/profiles/bigquery/profiles.yml
- integration_tests/profiles/redshift/profiles.yml
- integration_tests/profiles/snowflake/profiles.yml
- integration_tests/projects/000_fal_run/models/schema.yml
- integration_tests/projects/001_flow_run_with_selectors/fal_scripts/check_extra.py
- integration_tests/projects/001_flow_run_with_selectors/models/schema.yml
- integration_tests/projects/005_functions_and_variables/fal_scripts/complete_other_model.py
- integration_tests/projects/005_functions_and_variables/fal_scripts/write_to_source_twice.py
- integration_tests/projects/005_functions_and_variables/models/other_model.sql
- integration_tests/projects/005_functions_and_variables/models/schema.yml
- integration_tests/projects/005_functions_and_variables/models/some_model.sql
- integration_tests/projects/005_script_paths/models/schema.yml
- integration_tests/projects/profiles.yml
- src/faldbt/lib.py
Integration tests with profiles: https://github.com/fal-ai/fal/actions/runs/2242770108
> Fix Snowflake profile integration tests

- src/fal/el/fivetran.py
- src/faldbt/project.py
> Remove Literal usage in favor of checking with enum

- .github/workflows/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/ISSUE_TEMPLATE/config.yml
- .github/workflows/ISSUE_TEMPLATE/feature_request.md
This PR provides templates for feature request and bug issue templates in response to @chamini2 's comment about liking the format of this recent [bug report](https://github.com/fal-ai/fal/issues/282).
> [CHORE] feature request && bug issue templates

- integration_tests/features/flow_run.feature
- src/fal/cli/selectors.py
- src/fal/node_graph.py
We were taking the first level of ancestors. i.e., predecessors.
> Fix left-plus graph operator to take ALL ancestors

- integration_tests/features/flow_run.feature
- src/fal/cli/selectors.py
- src/fal/node_graph.py
- tests/graph/test_selectors.py
> Add plus-n operator like model+2 and 1+model

- src/faldbt/lib.py
- Process connection data from profile
- Update rename_relation to handle Athena renaming
- Pass location to adapter dialect properties
> WIP: Make write functions work on Athena

- docsite/docs/Reference/fal-scripts-path.md
- integration_tests/projects/006_script_paths/dbt_project.yml
- integration_tests/projects/006_script_paths/scripts/after.py
- integration_tests/projects/006_script_paths/scripts/utils/process/process_df.py
> Add another example for script paths import

- integration_tests/features/flow_run_middle_nodes.feature
- integration_tests/projects/002_jaffle_shop/fal_scripts/middle_script.py
- src/fal/cli/flow_runner.py
> fix: Offer real current status in fal flow for before/after scripts

- .github/workflows/test_profiles.yml
https://github.com/ben-z/gh-action-mutex/releases/tag/v1.0-alpha-5
> Replace fork of mutex GitHub action for original

- integration_tests/features/flow_run_middle_nodes.feature
- integration_tests/projects/008_pure_python_models/models/schema.yml
- src/fal/cli/selectors.py
Implements the [set intersection operator](https://docs.getdbt.com/reference/node-selection/set-operators#intersections) for selectors.
> feat: add support for using the set intersection operator on selectors

- integration_tests/features/execute_sql_function.feature
- integration_tests/projects/009_execute_sql_function/fal_scripts/run_macro.py
- integration_tests/projects/009_execute_sql_function/macros/multiply_by_ten.sql
- integration_tests/projects/009_execute_sql_function/models/schema.yml
> tests: use execute_sql to run macros

- README.md
- docsite/docs/Reference/variables-and-functions.md
> docs: add current list-models ui

- integration_tests/features/flow_run.feature
- integration_tests/features/steps/fal_steps.py
> test: integration tests for post hook features

- src/faldbt/project.py
- tests/mock/models/model_empty_fal.sql
- tests/mock/models/schema.yml
<details>
closes FEA-188
</details>
> fix: handle fal keyword being empty in schema.yml

- docsite/docusaurus.config.js
Links to https://featuresandlabels.notion.site/Public-Roadmaps-be3edf2bd5e841c490b7a228a5fc58c9
> docs: Point 'Roadmap' link to roadmaps index

- .github/workflows/pytest.yml
- poetry.lock
- pyproject.toml
- src/fal/planner/tasks.py
- tests/planner/test_tasks.py
> feat: Implement basic task units for parallelization

- src/fal/cli/model_generator/model_generator.py
This reverts commit 7589f6b41e362960d5c2ad5e0857eeb0f75a11c7.
> Revert "fix: before generating sql models delete old ones (#432)"

- src/fal/cli/flow_runner.py
- src/fal/planner/plan.py
- tests/planner/test_plan.py
- tests/planner/test_schedule.py
- tests/planner/utils.py
> feat: Add support for selections/exclusions in the planner

- src/fal/planner/executor.py
- src/fal/planner/schedule.py
- src/fal/planner/tasks.py
- tests/planner/test_plan.py
- tests/planner/test_schedule.py
- tests/planner/test_tasks.py
- tests/planner/utils.py
> feat: Implement error recovery for the parallel runner

- src/fal/planner/executor.py
> fix: use a general capture for multiprocessing / generator truthness

- integration_tests/features/python_nodes.feature
- integration_tests/projects/005_functions_and_variables/.gitignore
- integration_tests/projects/008_pure_python_models/.gitignore
- integration_tests/projects/008_pure_python_models/models/schema.yml
- integration_tests/projects/008_pure_python_models/scripts/before.py
- poetry.lock
- pyproject.toml
- src/fal/cli/flow_runner.py
- src/fal/cli/selectors.py
- src/fal/planner/plan.py
- tests/mock/mockTarget/run_results.json
- tests/planner/utils.py
Before _shuffling_ (I can change that name) them
And afterward
<details>
closes FEA-38
</details>
> feat: Make before/after scripts happen right before/after models

- src/fal/cli/cli.py
- tests/test_cli.py
> chore: remove warning about mutiple select flags being passed

- docsite/docs/Docs/compatibility.md
Seems like it is crashing the vercel deployment
> docs: change `<>`s to `&`

- src/fal/typing.py
- src/faldbt/project.py
- tools/generate_typing_context.py
> fix: Handle partially-applied write_to_model before scripts in typing module

- integration_tests/features/flow_run_middle_nodes.feature
- integration_tests/features/python_nodes.feature
- integration_tests/features/run.feature
- integration_tests/projects/000_fal_run/fal_scripts/pre_hook.py
- integration_tests/projects/000_fal_run/models/schema.yml
- integration_tests/projects/008_pure_python_models/models/schema.yml
- integration_tests/projects/008_pure_python_models/scripts/before.py
- integration_tests/projects/008_pure_python_models/scripts/pre_hook.py
- integration_tests/projects/011_highly_parallelizable/scripts/post_hook1.py
- integration_tests/projects/011_highly_parallelizable/scripts/post_hook2.py
- integration_tests/projects/011_highly_parallelizable/scripts/post_hook3.py
- src/fal/cli/fal_runner.py
- src/fal/fal_script.py
- src/fal/node_graph.py
- src/fal/planner/executor.py
- src/fal/planner/plan.py
- src/fal/planner/schedule.py
- src/fal/planner/tasks.py
- src/faldbt/project.py
- tests/_fal_testing/utils.py
- tests/planner/test_schedule.py
Here is a simple flow chart:
```mermaid
stateDiagram
state "Execute the main task" as task
state "Run the pre-hooks" as pre_hook
state "Run the post-hooks" as post_hook
[*] --> pre_hook
pre_hook --> task: on success
pre_hook --> post_hook: on failure
task --> post_hook: both on success and failure
post_hook --> [*]
```
> feat: Implement pre-hooks

- .github/workflows/pytest.yml
- .github/workflows/test_profiles.yml
- src/fal/cli/dbt_runner.py
https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.1#dependencies
> fix: ensure logbook doesn't crash on startup

- src/fal/cli/flow_runner.py
> feat: support script-only executions for fal_results.json

- src/fal/cli/selectors.py
- tests/graph/test_selectors.py
> fix: filter source nodes from nodes to run

- integration_tests/features/write_to_model_function.feature
- integration_tests/projects/005_functions_and_variables/models/model_with_array.py
- integration_tests/projects/005_functions_and_variables/models/model_with_date.py
- integration_tests/projects/012_model_generation_error/dbt_project.yml
- poetry.lock
- pyproject.toml
- src/fal/planner/executor.py
- src/faldbt/lib.py
https://github.com/snowflakedb/snowflake-connector-python/issues/544 manually resolved
Merge #487 before and use it's introduced artifact creation for tests.
<details>
Affected
- bigquery
- snowflake
</details>
> feat: optimize write and read for snowflake

- .github/workflows/test_profiles.yml
> tests: offer testing specific version on dispatch and test adapters mentioned in PR description

- integration_tests/features/context_info.feature
- integration_tests/features/steps/fal_steps.py
- integration_tests/features/write_to_model_function.feature
- integration_tests/features/write_to_source_function.feature
- integration_tests/projects/005_functions_and_variables/fal_scripts/context.py
- integration_tests/projects/005_functions_and_variables/models/schema.yml
- src/fal/fal_script.py
- src/fal/planner/tasks.py
- src/faldbt/project.py
- tests/_fal_testing/utils.py
- tests/planner/test_tasks.py
Adapters to test
- bigquery
- snowflake
- redshift
- postgres
- duckdb
> feat: offer adapter_response per model in CurrentModel class

- integration_tests/features/dbt_test.feature
- integration_tests/features/environment.py
- integration_tests/projects/002_jaffle_shop/fal_dbt.py
- integration_tests/projects/002_jaffle_shop/tests/customer_lifetime_value.sql
- src/fal/__init__.py
- src/faldbt/project.py
- tests/_fal_testing/utils.py
> feat: support singular tests

- integration_tests/features/context_info.feature
- integration_tests/features/meta_object.feature
- integration_tests/features/write_to_model_function.feature
- integration_tests/features/write_to_source_function.feature
- integration_tests/projects/005_functions_and_variables/fal_scripts/lists.py
- integration_tests/projects/005_functions_and_variables/models/schema.yml
- src/fal/typing.py
- src/faldbt/project.py
> feat: add support for sources meta property access in scripts context

- integration_tests/features/structured_hooks.feature
- integration_tests/projects/013_structured_hooks/models/fal/model_f.sql
- integration_tests/projects/013_structured_hooks/models/model_f.py
- integration_tests/projects/013_structured_hooks/models/schema.yml
- integration_tests/projects/013_structured_hooks/scripts/environment_type.py
- integration_tests/projects/013_structured_hooks/scripts/environment_type_2.py
- integration_tests/projects/013_structured_hooks/scripts/environment_type_3.py
- src/fal/fal_script.py
- src/fal/planner/tasks.py
- src/faldbt/parse.py
- src/faldbt/project.py
Implements the ability to specify the local (user's own environment) for hooks.
> feat: implement "local" hooks

- src/faldbt/lib.py
- src/faldbt/project.py
adapters to test:
- bigquery
- snowfkale
- redshift
- postgres
- athena
- duckdb
> refactor: pass config and adapter down to lib funcitons when possible

- src/fal/packages/bridge.py
- src/fal/packages/environments/base.py
- src/fal/packages/environments/virtual_env.py
- src/fal/planner/tasks.py
This is a pre-requisite for the conda implementation, pretty much a decoupling of the IPC protocol from the virtual env system (as well as other useful refactors)
> refactor: define the explicit flow between env<->conn

- src/faldbt/lib.py
adapters to test:
- bigquery
- snowflake
- postgres
> refactor: use sqlalchemy engine to write and read dataframes by default

- docsite/package-lock.json
> chore: run npm audit fix for docsite

- src/fal/packages/dependency_analysis.py
> fix: include fal-extras in the dependency analysis (and fix sf failures)

- .github/actions/setup-local-fal/action.yml
- .github/workflows/test_profiles.yml
- integration_tests/features/steps/fal_steps.py
- integration_tests/profiles/athena/profiles.yml
Test athena
Right now dbt-athena-adapter only supports dbt-core<=1.0, I will leave the 1.1 and 1.2 there and it will start testing correctly when it is available.
> tests: add athena integration tests

- .github/workflows/test_profiles.yml
- integration_tests/features/environment.py
- integration_tests/features/structured_hooks.feature
- integration_tests/projects/013_structured_hooks/fal_project.yml
- integration_tests/projects/013_structured_hooks/models/model_g.sql
- integration_tests/projects/013_structured_hooks/models/schema.yml
- integration_tests/projects/013_structured_hooks/scripts/check_imports.py
- integration_tests/projects/013_structured_hooks/scripts/environment_type.py
- integration_tests/projects/013_structured_hooks/scripts/environment_type_2.py
- integration_tests/projects/013_structured_hooks/scripts/environment_type_3.py
- src/fal/packages/dependency_analysis.py
- src/fal/packages/environments/__init__.py
- src/fal/packages/environments/base.py
- src/fal/packages/environments/conda.py
- src/fal/packages/environments/virtual_env.py
- src/fal/packages/isolated_runner.py
- src/fal/utils.py
- src/faldbt/parse.py
- tests/_fal_testing/utils.py
> feat: implement initial support for conda

- src/fal/packages/environments/base.py
- src/fal/packages/environments/conda.py
- src/fal/packages/environments/virtual_env.py
More description about the actual algoritm is under `DualPythonIPC` class.
> feat: generalize dual Python IPC and speed-up conda builds

- poetry.lock
- pyproject.toml
> misc: drop redundant dependencies to speed-up build times

- adapter/src/dbt/adapters/fal/connections.py
- adapter/src/dbt/adapters/fal/impl.py
- src/faldbt/adapters/python/__init__.py
- src/faldbt/adapters/python/connections.py
- src/faldbt/adapters/python/impl.py
> Add PythonAdapter and PythonConnectionManager classes

- src/faldbt/adapters/python/__init__.py
- src/faldbt/adapters/python/connections.py
- src/faldbt/adapters/python/impl.py
> feat: Add PythonAdapter and PythonConnectionManager classes

- src/fal/packages/environments/virtual_env.py
> Make environment inherit from local true by default (temporary)

- src/fal/packages/environments/conda.py
> Make conda environment support inheriting local environment

- .github/actions/setup-local-fal/action.yml
- .github/workflows/test_dbt_fal.yml
- adapter/compatible_adapters.txt
- adapter/pyproject.toml
- adapter/src/dbt/adapters/fal/adapter_support.py
- poetry.lock
- pyproject.toml
- src/fal/packages/isolated_runner.py
> ci: run jaffle shop for act1

- docsite/docs/Docs/fal-cli/environments.md
> doc: Document new environment management feature

- .github/pull_request_template.md
```md
- postgres
- 3.8
```
- postgres
- 3.8
> chore: easier to edit PR template

- docsite/docs/Reference/variables-and-functions.md
> doc: document `context.current_model.adapter_response`

- adapter/pyproject.toml
- adapter/src/dbt/adapters/fal/teleport.py
> fix: make teleport work with s3

- adapter/src/dbt/fal/adapters/python/impl.py
- postgres
- duckdb
- 3.8
- 3.7
> refactor: remove macro manifest from PythonAdapter

- docsite/docs/Docs/fal-cli/python-models.md
- docsite/package-lock.json
> docs: fal-model-paths for Python models

- adapter/src/dbt/adapters/fal/impl.py
- adapter/src/dbt/adapters/fal/teleport.py
- adapter/src/dbt/adapters/fal/teleport_adapter_support.py
- adapter/src/dbt/adapters/fal/teleport_support/snowflake.py
- adapter/src/dbt/include/fal/macros/teleport_snowflake.sql
Makes teleport between Snowflake and S3 possible
- 3.8
> feat: teleport between snowflake and S3

- integration_tests/features/context_info.feature
- integration_tests/features/meta_object.feature
- integration_tests/features/write_to_model_function.feature
- integration_tests/features/write_to_source_function.feature
- integration_tests/projects/005_functions_and_variables/fal_scripts/execute_sql.py
- integration_tests/projects/005_functions_and_variables/models/schema.yml
- src/faldbt/project.py
> fix: access compiled_code if compiled_sql is not present 

- adapter/pyproject.toml
- adapter/src/dbt/adapters/fal/wrappers.py
- adapter/src/dbt/adapters/fal_experimental/impl.py
- adapter/src/dbt/adapters/fal_experimental/telemetry/__init__.py
- adapter/src/dbt/adapters/fal_experimental/telemetry/telemetry.py
This removes the fal telemetry from #593 and adds new one for the adapter package.
For now it shares the same project API key.
We need to test before merging.
> chore(dbt-fal): add new telemetry to dbt-fal

- .github/workflows/test_profiles.yml
We are triggering unnecessary tests.
> tests(fal): ignore adapter changes for fal test trigger

- adapter/pyproject.toml
- adapter/src/dbt/adapters/fal_experimental/adapter_support.py
- adapter/src/dbt/adapters/fal_experimental/support/bigquery.py
Use solution heavily based on fal lib.py
> feat(dbt-fal): optimize bigquery read and write

- .github/workflows/test_cli.yml
- .github/workflows/test_integration_adapter.yml
- .github/workflows/test_integration_cli.yml
- adapter/tests/test_dbt_fal.py
This will trigger more relevant tests in general.
> tests: better triggering of tests and name of files

- .github/workflows/python-release.yml
looks good: https://github.com/fal-ai/fal/pull/631
> chore: fix release script 

- adapter/pyproject.toml
> docs(dbt-fal): add readme, homepage and others for PyPI

- .github/workflows/test_integration_adapter.yml
- adapter/integration_tests/profiles/redshift/profiles.yml
- adapter/poetry.lock
- adapter/pyproject.toml
- Fixes installation of dbt-fal with `pip install dbt-fal[redshift]`
- Adds redshift to integration tests
> fix(dbt-fal): make dbt-fal work with redshift

- .github/workflows/python-release.yml
https://github.com/fal-ai/fal/pull/657/files
to fix
```
dbt --version
```
> chore(dbt-fal): Bump the version of dbt.adapters.fal in GH relase action

- adapter/src/dbt/adapters/fal/impl.py
Before:
```
❯ python
Python 3.8.13 (default, Sep 30 2022, 17:13:29)
[Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fal
>>> fal.FalDbt('.', '~/.dbt')
usage: dbt [-h] [--version] [-r RECORD_TIMING_INFO] [-d] [--log-format {text,json,default}] [--no-write-json] [--use-colors | --no-use-colors] [--printer-width PRINTER_WIDTH] [--warn-error] [--no-version-check]
[--partial-parse | --no-partial-parse] [--use-experimental-parser] [--no-static-parser] [--profiles-dir PROFILES_DIR] [--no-anonymous-usage-stats] [-x] [--event-buffer-size EVENT_BUFFER_SIZE] [-q]
[--no-print] [--cache-selected-only | --no-cache-selected-only]
{docs,source,init,clean,debug,deps,list,ls,build,snapshot,run,compile,parse,test,seed,run-operati …
```
> fix(dbt-fal): stop parsing the entire command args

- .github/workflows/python-release.yml
We were setting it _before_ we sent it to PyPI.
> chore(dbt-fal): Set the version before building so it gets deployed to PyPI

- README.md
- docsite/docs/fal/fal-dbt/model-scripts.md
- docsite/docs/fal/reference/fal-scripts-path.md
> Fix docs for post-hook

- README.md
> Add link for dbt Slack channel

- docsite/docs/fal/fal-dbt/fal-el-jobs.md
- docsite/docs/fal/fal-dbt/global-scripts.md
- docsite/docs/fal/fal-dbt/model-scripts.md
- docsite/docs/fal/fal-dbt/python-models.md
- docsite/docs/fal/fal-dbt/refs-sources-context.md
- docsite/docs/fal/guides/python-models-migration.md
- docsite/docs/fal/python-package.md
- docsite/docs/fal/quickstart.md
- docsite/docs/fal/reference/fal-scripts-path.md
- docsite/docs/fal/reference/variables-and-functions.md
> Fixing broken docs links

- .github/workflows/test_integration_adapter.yml
- adapter/integration_tests/profiles/bigquery/profiles.yml
- adapter/src/dbt/adapters/fal_experimental/adapter.py
> tests(dbt-fal): run fal cloud tests on bigquery

- src/faldbt/lib.py
fixes write error to bigquery
- bigquery
- 3.8
- 3.7
- 3.9
- 3.10
> fix: bigquery write relation

- adapter/src/dbt/adapters/fal_experimental/utils/environments.py
> fix: change how dbt-fal version is put together

- adapter/integration_tests/features/steps/fal_adapter_steps.py
- adapter/integration_tests/projects/simple_project/dbt_project.yml
- adapter/integration_tests/projects/simple_project/models/base/model_a.sql
- adapter/integration_tests/projects/simple_project/models/base/model_b.sql
- adapter/integration_tests/projects/simple_project/models/python/model_c.py
- adapter/integration_tests/projects/simple_project/models/schema.yml
> tests(dbt-fal): add resource-paths to dbt_project.yml to make sure it is picked up by dbt

- adapter/src/dbt/adapters/fal/wrappers.py
We were getting reports of slow `dbt seed` times and even saw that it applied to some other dbt tasks too.
Thanks to @daveworth pointing out we added an `inspect.stack()` call in #691 that may be slow!
This analysis of the stack is necessary to decide if we should return `fal` or the DB adapter type in the `adapter.type()` call. This is to make dbt packages that make decisions based on `adapter.type()` work.
This approach reduces time greatly because `inspect.stack()` by default loads the file of each function in the stack to take some context to show (some lines).
The time difference I am seeing with the seed data from https://github.com/fal-ai/jaffle_shop_with_fal is:
Base comparison WITHOUT dbt-fal:
```
❯ dbt seed # dbt-postgres
23:11:41  Running with dbt=1.3.2
23:11:41  Unable to do …
```
> fix(dbt-fal): faster inspect stack by using manual solution without loading source code

- src/fal/cli/cli.py
Small deprecation housekeeping.
> chore: remove deprecation warning

- .github/workflows/test_integration_adapter.yml
- adapter/compatible_adapters.txt
- adapter/poetry.lock
- adapter/pyproject.toml
- adapter/src/dbt/adapters/fal_experimental/support/snowflake.py
- adapter/src/dbt/adapters/fal_experimental/teleport_support/duckdb.py
- adapter/src/dbt/adapters/fal_experimental/utils/environments.py
- adapter/src/dbt/fal/adapters/python/connections.py
- adapter/src/dbt/fal/adapters/python/impl.py
- adapter/src/dbt/fal/adapters/teleport/impl.py
- postgres
- bigquery
- duckdb
- snowflake
- redshift
- 3.8
- 3.10
> chore(dbt-fal): Update for 1.4 dbt-core support 

- projects/adapter/src/dbt/adapters/fal_experimental/utils/environments.py
- projects/fal/src/fal/packages/dependency_analysis.py
> fix: install fal and adapter local prereleases correctly

- projects/adapter/README.md
- projects/fal/README.md
An example can be found in https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_base_test
There is a discussion on [pypa](https://github.com/pypa/readme_renderer/issues/163) from 2020 about this.
> docs: Try to fix PyPI relative links with HTML base tag

- docsite/docs/dbt-fal/cloud/using_fal_cloud.md
- projects/adapter/src/dbt/adapters/fal_experimental/connections.py
Resolve `host=cloud` to `api.alpha.fal.ai`
- postgres
- bigquery
- 3.9
> feat(dbt-fal): `cloud` host resolution

- projects/fal/src/fal/fal_script.py
- projects/fal/src/faldbt/project.py
global and hook information on scripts.
- postgres
- 3.8
> feat: send fal script telemetry info

- .github/workflows/test_integration_adapter.yml
- projects/adapter/integration_tests/configs/sqlserver/docker-compose.yml
- projects/adapter/integration_tests/features/steps/fal_adapter_steps.py
- projects/adapter/integration_tests/profiles/sqlserver/profiles.yml
- projects/adapter/src/dbt/adapters/fal_experimental/adapter_support.py
Adds support for sqlserver adapter
Closes #778
> feat(dbt-fal): make dbt-fal work with sqlserver

- .github/workflows/test_integration_adapter.yml
- .gitignore
- adapter/integration_tests/configs/sqlserver/docker-compose.yml
- adapter/integration_tests/features/steps/fal_adapter_steps.py
- adapter/integration_tests/profiles/sqlserver/profiles.yml
- adapter/src/dbt/adapters/fal_experimental/adapter_support.py
Adds sqlserver adapter support
> feat(dbt-fal): support sqlserver

- .github/workflows/test_integration_adapter.yml
- projects/adapter/integration_tests/features/source.feature
- projects/adapter/integration_tests/profiles/athena/profiles.yml
- projects/adapter/src/dbt/adapters/fal/wrappers.py
- projects/adapter/src/dbt/adapters/fal_experimental/adapter_support.py
- projects/adapter/src/dbt/adapters/fal_experimental/impl.py
- projects/adapter/src/dbt/adapters/fal_experimental/support/athena.py
- projects/adapter/src/dbt/adapters/fal_experimental/utils/environments.py
This is just a rebase and a small fix of #750 
- postgres
- athena
> fix: athena community

- projects/adapter/poetry.lock
- projects/adapter/pyproject.toml
Looks like there are some breaking changes in the latest fal-serverless/isolate-proto update.
> fix(adapter): fal-serverless dependency

- docsite/package-lock.json
- docsite/package.json
Quick chore to upgrade docusaurus from beta to the latest version. Not urgent but wanted to do it before upgrading becomes a hassle.
_Signed by a guy traumatized by years of JS library upgrades._
> chore(docsite): upgrade docusaurus

- .github/workflows/test_integration_cli.yml
> tests: turn off slack messages

- docsite/docs/fal-serverless/isolated_functions/scheduling.md
Documentation updates for scheduled functions.
> feat(docsite): add fal-serverless scheduled docs

- examples/anomaly-detection/README.md
> docs: fix example file path

- projects/adapter/integration_tests/features/commands.feature
- projects/adapter/integration_tests/features/steps/fal_adapter_steps.py
to make sure they work before next releases
> tests(dbt-fal): add dbt debug and dbt --version calls

- .github/workflows/test_integration_adapter.yml
- projects/adapter/src/dbt/adapters/fal/wrappers.py
> fix(dbt-fal): sqlserver quoting policy

- .github/workflows/python-release.yml
> fix: pin newer poetry version to avoid urllib3 error

- projects/adapter/integration_tests/projects/simple_project/dbt_project.yml
- projects/adapter/integration_tests/projects/simple_project/models/base/python/model_c.py
- projects/adapter/integration_tests/projects/simple_project/models/model_d.sql
Just for example purposes, not really used.
> tests: modify adapter tests for post-hooks

- projects/fal/poetry.lock
- projects/fal/pyproject.toml
- projects/fal/src/fal/cli/args.py
- projects/fal/src/fal/cli/cli.py
- postgres
- snowflake
- bigquery
- redshift
- duckdb
- athena
- 3.7
- 3.11
> chore: Remove koldstart from fal

- projects/fal/poetry.lock
- projects/fal/pyproject.toml
- postgres
- snowflake
- bigquery
- redshift
- duckdb
- athena
- 3.8
- 3.11
closes FEA-878
closes #871
> feat: support python 3.11

- examples/metric-forecast/README.md
> Typo in README.md histotic -> historic
