fal-ai/dbt-fal

src/fal/cli.py, src/faldbt/parse.py
Should I keep `--dbt-dir`? I thought we could match dbt's flags.
=> Change --dbt-dir for --project-dir and handle relative paths

src/faldbt/parse.py, src/faldbt/project.py
=> Handle run results not being present for some models

pyproject.toml, src/fal/cli.py
```
❯ fal --version
fal, version 0.1.0
❯ fal --help
Usage: fal [OPTIONS] COMMAND [ARGS]...
Options:
--version  Show the version and exit.
--help     Show this message and exit.
Commands:
run
❯ fal run --help
Usage: fal run [OPTIONS]
Options:
--project-dir PATH   Directory to look for dbt_project.yml.
--profiles-dir PATH  Directory to look for profiles.yml.
--keyword TEXT       Property in meta to look for fal configurations.
--all                Only run models that ran in the last dbt run.
--debug              Display debug logging during execution.
--help               Show this message and exit.
```
=> Better usage of click for help flag

README.md, src/faldbt/parse.py
Added needed enum for `context.current_model.status` and documented through examples instead of explaining. Feedback welcome.
=> Document write_to_source and refactor variables section

poetry.lock, pyproject.toml, src/fal/run_scripts.py
usage:
```
df = ref('model_name')
write_firestore(
df=df, 
collection="collection_name", 
document="document_name", 
key_column="column_name", 
merge=True)
```
where `key_columns` and `merge` are optional arguments. The default value for `key_column` is a index + 1 of an entry in a dataframe. `merge` controls whether the dataframe data should be added to an existing document.
=> Add firestore_writer

.github/workflows/integration_tests.yml
Adds a workflow that runs integrations tests:
- uses https://github.com/fal-ai/fal_dbt_test
- runs dbt and fal
- checks fal script outputs
=> Add integration test github action workflow

src/faldbt/lib.py
Trying to solve for this issue: https://github.com/fal-ai/fal_dbt_examples/runs/4526303392?check_suite_focus=true
As said in https://github.com/sqlalchemy/sqlalchemy/discussions/7459, it may be a sqlalchemy-bigquery bug
=> Use create_mock_engine to avoid connections

src/fal/cli.py, src/faldbt/project.py
FalDbt should be aware of fal meta keyword for future use cases.
When a user initializes FalDbt in a Python environment, they can now specify a keyword:
```
fal = FalDbt(project_dir='my_proj', profiles_dir='my_profile', keyword='my_fal')
```
=> Move meta keyword from FalProject to FalDbt

src/faldbt/project.py
As seen in [Pandas docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.from_records.html#pandas.DataFrame.from_records)
> coerce_float : bool, default False
> Attempt to convert values of non-string, non-numeric objects (like decimal.Decimal) to floating point, useful for **SQL result set**
=> Coerce float results

src/fal/cli.py
Adds `--script` option:
```
fal run --select my_model --script my_script1.py --script my_script2.py
```
here scripts specified in schema.yml are overridden. If more than one model is selected, all scripts run on all models.
=> Select scripts option

.github/workflows/integration_tests.yml, README.md, src/fal/run_scripts.py, src/faldbt/project.py
Closes: #101 
context object has access to test information related to the current model. If the previous dbt command was either `test` or `build`, the context.current_model.test property is populated with a list of tests:
```
context.current_model.tests
#= [CurrentTest(name='not_null', modelname='historical_ozone_levels', column='ds', status='Pass')]
```
=> Make fal aware of dbt test results

src/fal/cli.py, tests/test_cli.py
Now both `fal run -s a b` and `fal run -s a -s b` work to maintain backwards compatibility with 0.1.38
=> Backwards compatible select/model flags

src/fal/cli.py
I focused in #132 on select and models and forgot about `exclude`. I also added `scripts` to maintain the same behavior across flags.
What do you think? Should we merge this or is it ok how it is?
*****
Current behavior
```
fal run --select a --select b --exclude c --exclude d
```
Behavior in this branch
```
fal run --select a --select b --exclude c --exclude d
```
*****
=> Add extend action for exclude and scripts flags

README.md, docsite/docs/cli/fal scripts/lifecycle.md, docsite/docs/cli/fal scripts/model-scripts-selection.md, docsite/docs/cli/getting-started.md, src/fal/cli.py
New warning:
```
$ fal run --profiles-dir . -s boston -s lombardia_covid -m boston
23:45:44  Found 6 models, 0 tests, 0 snapshots, 0 analyses, 188 macros, 0 operations, 2 seed files, 1 source, 0 exposures, 0 metrics
23:45:44  [WARNING]: Passing multiple --select/--model flags to fal is deprecatd.
Please use model selection like dbt. Use: --select boston lombardia_covid boston
```
=> Change readme for modified selection flags

README.md, src/faldbt/lib.py, src/faldbt/project.py
Addresses #120 
When calling `write_source` user now has one optional argument: `dtype`, which works the same way as described here: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sql.html
=> Add dtypes args to write_to_source

src/fal/cli.py, src/faldbt/parse.py, tests/test_project.py
When you pass model selection of `--before` flag, global scripts are not run.
=> Enable --before for global scripts

src/fal/cli/__init__.py, src/fal/cli/args.py, tests/test_cli.py
We had a problem when using flags like `fal --profiles-dir . run` vs `fal run --profiles-dir .`, which should behave the same.
This has a "hack" where we create several `dest` for each of these flag positions, but it is all abstracted in the args file.
=> Handle flags present in several commands and subcommands

src/fal/el/airbyte.py, src/fal/fal_script.py, src/faldbt/el_client.py, src/faldbt/parse.py, src/faldbt/project.py, tests/mock/mockProfile/profiles.yml, tests/test_el/test_fivetran.py, tests/test_project.py
- Magic functions `airbyte_sync` and `fivetran_sync`
- Setting EL client properties in profiles.yml
Users can now define EL client properties in a profile:
```yaml
fal_test:
target: dev
fal_extract_load:
dev:
- name: 'my_fivetran_el'
type: fivetran
api_key: my_fivetran_key
api_secret: my_fivetran_secret
connectors:
- name: fivetran_connector_1
id: id_fivetran_connector_1
- name: fivetran_connector_2
id: id_fivetran_connector_2
- name: 'my_airbyte_el'
type: airbyte
host: http://localhost:8001
connections:
- name: airbyte_connection_1
id: id_airbyte_connection_1
- name: airbyte_connection_2
id: id_airbyte_connection_2
outputs:
dev:
type: postgres
host: localhost
user: pguser
password: pass
port: 5432
dbname: test
schema: dbt_fal
threads: 4
```
`dev` under `fal_extract_load` is a target and …
=> Set EL API client parameters in profiles.yml

src/fal/telemetry/telemetry.py
Hack while in https://github.com/PostHog/posthog-python/pull/52 gets addressed.
=> Add hack to avoid unclosed ssl warning 

integration_tests/mock/fal_scripts/john_test.py, integration_tests/mock/fal_scripts/test.py, integration_tests/mock/fal_scripts/utils/model_info.py, integration_tests/mock/fal_scripts/utils/my_util.py, src/fal/fal_script.py, src/fal/run_scripts.py
Now it looks like:
```
Error in script /Users/matteo/Projects/fal/fal/integration_tests/mock/fal_scripts/test.py with model zendesk_ticket_data:
Traceback (most recent call last):
File "/Users/matteo/Projects/fal/fal/src/fal/run_scripts.py", line 68, in _prepare_exec_script
script.exec(context, faldbt)
File "/Users/matteo/Projects/fal/fal/src/fal/fal_script.py", line 36, in exec
exec(
File "/Users/matteo/Projects/fal/fal/integration_tests/mock/fal_scripts/test.py", line 5, in <module>
model_info = model_info_str(context.current_model)
File "/Users/matteo/Projects/fal/fal/integration_tests/mock/fal_scripts/utils/model_info.py", line 6, in model_info_str
return outputs
NameError: name 'outputs' is not defined
```
Notice the file is accurate, vs `<string>` before.
=> Better stack trace for errors in user scripts 

src/fal/cli/cli.py, src/fal/telemetry/telemetry.py, tests/test_telemetry.py
I was getting errors when sending the information like
```
Dictionary values must be serializeable to JSON "exception" value <class 'RuntimeError'> of type <class 'type'> is unsupported.
```
=> Handle exceptions better in telemetry

integration_tests/projects/002_jaffle_shop/load_data.py
This test was doing a `ref(context.current_model.name)` in a `before` script. For clean environments (GitHub actions), there was no data yet. 
This exposes a possible problem for other tests that we clean the directories but do not truncate the whole database between tests. I will look into that.
=> Remove ref to non-yet-existent relation in integration test

integration_tests/features/environment.py, integration_tests/features/flow_run.feature, integration_tests/features/steps/fal_steps.py, integration_tests/projects/001_flow_run_with_selectors/fal_scripts/check_extra.py, integration_tests/projects/001_flow_run_with_selectors/models/schema.yml, integration_tests/projects/001_flow_run_with_selectors/models/zendesk_ticket_data.sql, src/fal/cli/args.py, src/fal/cli/cli.py, src/fal/cli/dbt_runner.py, src/fal/telemetry/telemetry.py, src/faldbt/parse.py, tests/test_cli.py, tests/test_telemetry.py
Maybe we should set environment variables in the scripts when running. But if we do that, we should read `dbt_project.yml#vars` too.
closes #253
=> Add vars flag for fal flow run and pass to dbt 

integration_tests/features/flow_run.feature, src/fal/cli/args.py, src/fal/cli/dbt_runner.py, src/fal/cli/fal_runner.py, src/fal/telemetry/telemetry.py, src/faldbt/project.py, tests/test_cli.py
You can now run:
```
fal flow run --target my_custom_target
```
and
```
fal run --target my_custom_target
```
In `fal run` the `--target` argument will take precedent over the target specified in run_results.json.
=> Add --target arg to `fal run` and `fal flow run`

integration_tests/projects/005_functions_and_variables/fal_scripts/complete_other_model.py, src/fal/fal_script.py, src/faldbt/project.py
We used to accept `ref('model', 'package')`, it should match dbt `ref('package', 'model')`
=> Swap ref and write_to_model package and model arguments

src/fal/cli/args.py, src/fal/cli/cli.py, src/fal/cli/fal_runner.py, tests/mock/models/other_with_scripts.sql, tests/mock/models/schema.yml, tests/test_cli.py
We had warned we would remove support for this in 0.4, but Python 3.7 does not support extend action. I think we can prioritize Python 3.7
For #274
=> Remove support passing --select/--script/--exclude flags multiple times

src/fal/fal_script.py, src/faldbt/project.py
=> Remove slash arg to have only-positional arguments

src/faldbt/magics.py
Initialize fal magic variables inside a notebook. Must provide `project_dir` and `profiles_dir`.
In a notebook:
```
from faldbt.magics import init_fal
```
This makes `init_fal` line magic command available:
```
%init_fal project_dir=/my_project_dir profiles_dir=/my_profiles_dir
```
Now fal magic functions are available:
```
my_models = list_models()
my_df = ref('my_model')
```
- Couldn't find a simple way to test this, use of magic decorators requires being inside a notebook runtime.
=> Offer `init_fal` iPython magic command

integration_tests/projects/007_ipynb_scripts/fal_scripts/notebooks/my_notebook.ipynb, src/faldbt/magics.py
Looks like there isn't an easy way to find a file name for Jupyter Notebook: https://stackoverflow.com/questions/52119454/how-to-obtain-jupyter-notebooks-path
So, instead, in this PR we ask the user to enter the target model name:
```
%init_fal project_dir=../.. profiles_dir=../../.. default_model_name=zendesk_ticket_data
```
`default_model_name` is can be overridden by fal during fal runtime.
=> Make ipynb write_to_model work with a default model name

src/fal/cli/model_generator/deps_generator.py
> Deprecated since version 3.8: Old classes ast.Num, ast.Str, ast.Bytes, ast.NameConstant and ast.Ellipsis are still available, but they will be removed in future Python releases. In the meantime, instantiating them will return an instance of a different class.
So we need to check `ast.Str` for 3.7
closes FEA-83
=> fix: Change dbt functions args check for ast.Str that works on all versions

.github/workflows/test_profiles.yml, poetry.lock, pyproject.toml
We don't actually run the `prophet` scripts in integration tests.
=> chore: Support Python 3.10

integration_tests/features/environment.py, integration_tests/features/steps/fal_steps.py, src/fal/cli/flow_runner.py
=> fix: Handle only-script fal flow run

.github/workflows/integration_tests.yml, .github/workflows/pytest.yml
Opinions if we should do this are welcome.
=> chore: Add latest dbt version to tests

src/fal/cli/fal_runner.py, src/faldbt/project.py
<details>
closes FEA-115
</details>
=> fix: Process passed paths in FalDbt init and expand user

integration_tests/features/run.feature, integration_tests/projects/000_fal_run/fal_scripts/after.py, integration_tests/projects/000_fal_run/models/agent_wait_time.sql, src/fal/fal_script.py, src/faldbt/lib.py, src/faldbt/project.py
=> feat: show dbt model aliases

integration_tests/features/main_module.feature, integration_tests/projects/002_jaffle_shop/fal_scripts/main_check_2.py, integration_tests/projects/002_jaffle_shop/fal_scripts/middle_script.py, src/fal/fal_script.py
<details>
closes #328 
closes FEA-95
</details>
=> feat: Set __name__ as __main__ for scripts ran

integration_tests/features/write_to_model_function.feature, integration_tests/features/write_to_source_function.feature, integration_tests/projects/005_functions_and_variables/fal_scripts/complete_model.py, integration_tests/projects/005_functions_and_variables/models/schema.yml, integration_tests/projects/005_functions_and_variables/models/third_model.sql
Looks like write_to_model already works on models with aliases.
Modified write_to_model test to include a model with alias.
closes FEA-119
=> Test write-to-model with model alias

src/fal/fal_script.py, src/fal/run_scripts.py, src/fal/utils.py
How the logs would look now:
```
19:25:00  Unable to do partial parsing because config vars, config profile, or config target have changed
19:25:01  Found 5 models, 0 tests, 0 snapshots, 0 analyses, 167 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
Executing command: dbt --log-format json run --project-dir /Users/matteo/Projects/fal/fal/integration_tests/projects/008_pure_python_models --select model_a model_c model_b
Running with dbt=1.1.0
Found 5 models, 0 tests, 0 snapshots, 0 analyses, 167 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
Concurrency: 4 threads (target='dev')
1 of 2 START view model dbt_fal.model_a ........................................ [RUN]
1 of 2 OK created view model dbt_fal.model_a ................................... …
```
=> feat: Log script id with path relative to scripts_path or project_dir

integration_tests/features/dbt_test.feature, integration_tests/projects/005_functions_and_variables/fal_scripts/write_to_source_twice.py, integration_tests/projects/005_functions_and_variables/models/schema.yml, src/faldbt/project.py, tests/test_import.py
`list_sources` now returns a list of `DbtSource` objects that have a `tests` property and a `status` property.
Closes #336 
closes fea-109
=> feat: make source test data available in context

.github/workflows/test_profiles.yml
this is to support skipping test cases by profile like:
```
@TODO-duckdb
Scenario: Use write_to_model and write_to_source function with mode overwrite
When the following command is invoked:
"""
fal flow run --profiles-dir $profilesDir --project-dir $baseDir --experimental-flow
"""
Then the following models are calculated:
| other_model | some_model |
And the following scripts are ran:
| some_model.write_to_source_twice.py | other_model.complete_other_model.py |
And the script other_model.complete_other_model.py output file has the lines:
| my_float None | my_float 2.3 | size 1 |
And the script some_model.write_to_source_twice.py output file has the lines:
| my_float 2.3 |
```
=> chore: add @TODO-profile tag to skip tests by profile

integration_tests/features/dbt_test.feature, integration_tests/features/flow_run.feature, integration_tests/features/flow_run_middle_nodes.feature, integration_tests/features/flow_run_with_jaffle_shop.feature, integration_tests/features/globals.feature, integration_tests/features/ipynb_scripts.feature, integration_tests/features/python_nodes.feature, integration_tests/features/run.feature, integration_tests/features/run_with_custom_target.feature, integration_tests/features/steps/fal_steps.py, integration_tests/features/write_to_source_function.feature
- `following scripts are ran` checks are now exhaustive. They need to include all the scripts that are ran on the **last** invoked command.
- For preventing conflicts (e.g on a invocation-chain when the initial command runs some scripts and the actual tested command runs a different set of scripts), we now clear all the fal-related artifacts at each session. This is similiar how DBT's run file is overwriten at every time. 
- Adjusted existing cases of `following scripts are ran` to the current format.
- Removed some redundant cases of `following scripts are not ran` cases (if there is a preceding `following scripts are ran` check, that means this case is now redundant. Didn't remove all of them since there are still some valid usages).
=> tests: exhaustive check for scripts that are ran

integration_tests/features/flow_run_middle_nodes.feature, integration_tests/features/python_nodes.feature, integration_tests/features/steps/fal_steps.py, integration_tests/projects/008_pure_python_models/models/model_e.ipynb, integration_tests/projects/008_pure_python_models/models/staging/model_c.py
As discussed in FEA-37, the convention is `<model>.txt` for output files and `<model>.{py, ipynb}` in the feature files. Blocked by: #361
=> tests: add support for testing pure-python models

.gitignore
>  For a library or package, you might want to ignore these files since the code is
>   intended to run in multiple environments; otherwise, check them in:
<details>
closes FEA-152
</details>
=> chore: ignore .python-version file

.github/workflows/test_profiles.yml
Now manually triggering a "different profiles" GH Action will only test on `3.8` to reduce usage.
https://github.com/fal-ai/fal/actions/runs/2464247613
=> tests: Test all Python versions supported only for scheduled runs

docsite/docusaurus.config.js, docsite/package-lock.json, docsite/package.json
Adds a search button with locally indexed search functionality
=> docs: add simple search

integration_tests/features/flow_run_middle_nodes.feature, integration_tests/features/flow_run_with_jaffle_shop.feature, src/fal/cli/selectors.py
- Add support for `--select` with `"x y z"` (more discussion [here](https://github.com/fal-ai/fal/pull/353#discussion_r891072798)).
- Remove the `SetOperator` (noticed it was easier if we don't depend on it since we only have 2 operators).
=> feat: support quote-grouped `--select` arguments

src/faldbt/lib.py
This avoids getting a 404 error and then creating, which sometimes is cached by the BigQuery service and then reports a 404 even when the table has just been created.
https://github.com/googleapis/google-cloud-go/issues/975#issuecomment-383294334
> I think you answered your own question. Creating a table is an eventually consistent operation: it may not appear to exist everywhere until after some time has passed. In the screenshots above, the second request, which happens 2 seconds after the first, may end up at a different location where the creation hasn't yet propagated.
I think this works. There is no real way to test but to release it to users and await complaints.
<details>
closes FEA-156
</details>
=> fix: Replace table instead of dropping and renaming for BigQuery

integration_tests/features/flow_run_order.feature, integration_tests/features/python_nodes.feature, integration_tests/features/steps/fal_steps.py, integration_tests/projects/008_pure_python_models/models/schema.yml
- Added support for the `Then the following nodes are calculated in the following order` condition
- This internally collects all DBT models and their calculation (execution) time, as well as the the modification time of the Fal artifacts (from Python models or Python scripts). Which is then leveraged into sorting the list of calculated nodes.
- Also does some refactorings on the collection of models/scripts, unifies most of the logic into a single core function we need to adapt if we change the format and a couple upper level functions.
=> tests: allow testing the execution/calculation order of nodes

.github/workflows/test_profiles.yml
=> tests: Notify also cancelled tests and change check to schedule

src/faldbt/project.py
This is what printing a DbtModel object will look like:
```
DbtModel(name='zendesk_ticket_data', alias='fal_000_zendesk_ticket_data', unique_id='model.fal_000.zendesk_ticket_data', columns={}, tests=[], status=<NodeStatus.Success: 'success'>)
```
=> chore: add status to DbtModel repr

integration_tests/projects/000_fal_run/fal_scripts/write_to_model.py, integration_tests/projects/000_fal_run/fal_scripts/write_to_source.py, src/fal/fal_script.py
<details>
closes FEA-187
</details>
=> fix: Handle any number of args for not allowed functions in post-hooks

src/fal/cli/args.py, src/fal/cli/flow_runner.py
Only adds the flag (doesn't add anything in terms of the implementation) and splits the `fal flow run` into two isolated parts (so we can plug the threaded executor once we need it).
=> feat: Add `--experimental-threads=` flag

integration_tests/features/flow_run_order.feature, integration_tests/features/steps/fal_steps.py
We are switching from tables to our own format, since tables in cucumber needs to have the exact same number of columns in each row which is something that doesn't quite work for us (see the examples below). This PR adds a new way to write order based tests, with the ability of specifiying whether a row might be executed in parallel.
```
Then the following nodes are calculated in the following order:
"""
1. model_a, model_a.after.py, model_b, model_c.py
2. (unordered) model_c.post_hook.py, model_c.after.py
3. (unordered) model_d, model_e.ipynb, model_e.after.py
"""
```
=> tests: allow representing parallel executions in order tests

.github/ISSUE_TEMPLATE/bug_report.md
Sometimes `Paste the following commands output` with indentation would break the formatting.
=> chore: Bug report template details

src/faldbt/lib.py
This avoids race conditions when writing to the same table from 2 different scripts in parallel.
=> fix: add uniqueness to temp tables

.github/workflows/integration_tests.yml, integration_tests/features/flow_run.feature, src/faldbt/lib.py, src/faldbt/project.py
From the logs I got from a user, which had this:
```
...
dbt.exceptions.InvalidConnectionException: Runtime Error
connection never acquired for thread (6013, 140139196045056), have []
```
I remembered having this same issue when introducing parallelization. So I looked at the relevant code changes and found 
https://github.com/fal-ai/fal/blob/9aec7f15277e01c47597898d647e93d828c89212/src/faldbt/lib.py#L77
Commit: https://github.com/fal-ai/fal/commit/7d9d3738fae255a6851c89a12d92eb8db24efb6f#diff-644c7d4ee481dd1f7f2e070dc15c876e1d4c6b84af31ae5ce8fade10ef136d52L77-L78
Which was the culprit for that problem. But we also had introduced those instructions in compile_sql because it would not work without it.
https://github.com/fal-ai/fal/blob/fc8e0b68d84a8a7400d68832f97ae1f79a1fd0e7/src/faldbt/lib …
=> fix: stop resetting adapters to avoid connections being lost

integration_tests/projects/008_pure_python_models/scripts/post_hook.py
The `features/flow_run_order.feature:50` test randomly fails, and from what I've gathered it seems like the timings are the problem. I am not sure whether it is definitely resolved, but I've run it ~10 times locally and it didn't fail yet.
=> tests: add a little delay to the post-hook script

.github/workflows/integration_tests.yml, integration_tests/features/write_to_model_function.feature, integration_tests/projects/005_functions_and_variables/fal_scripts/complete_model.py, integration_tests/projects/005_functions_and_variables/fal_scripts/write_to_source_twice.py, integration_tests/projects/005_functions_and_variables/models/model_with_array.py, integration_tests/projects/005_functions_and_variables/models/model_with_date.py, integration_tests/projects/005_functions_and_variables/models/other_model.sql, integration_tests/projects/005_functions_and_variables/models/schema.yml, integration_tests/projects/005_functions_and_variables/models/some_model.sql, integration_tests/projects/005_functions_and_variables/models/third_model.sql, integration_tests/projects/008_pure_python_models/models/staging/model_c.py, src/faldbt/lib.py, src/faldbt/project.py
4.3m+ rows in BigQuery being read and written (I don't have the best internet...)
```
❯ fal flow run --select @questions --profiles-dir . --experimental-models
20:26:52  Unable to do partial parsing because config vars, config profile, or config target have changed
20:26:53  Found 9 models, 0 tests, 0 snapshots, 0 analyses, 191 macros, 0 operations, 3 seed files, 3 sources, 0 exposures, 0 metrics
Could not read dbt sources artifact
Executing command: dbt --log-format json run --project-dir /Users/matteo/Projects/fal/fal_dbt_examples --profiles-dir . --select stackoverflow_questions_small questions questions_analysis
Running with dbt=1.1.0
Found 9 models, 0 tests, 0 snapshots, 0 analyses, 191 macros, 0 operations, 3 seed files, 3 sources, 0 exposures, 0 metrics
The selection criterion …
```
=> feat: BigQuery improvements for table write and replace

docsite/docs/Docs/credentials-profile.md
Noticed a small typo as I was going through the documentation, so thought I'd submit an equally small patch.
=> docsite/docs: patch typo

integration_tests/features/flow_run.feature, src/fal/cli/selectors.py
This used to fail, now we just skip those failures (since DBT already shows the selection does not match any nodes, we don't need any extra logging).
```
$ temp_dir=$(mktemp -d) fal flow run --profiles-dir ../ --select model_X+     
12:39:41  [WARNING]: Deprecated functionality
The `source-paths` config has been renamed to `model-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
12:39:41  [WARNING]: Deprecated functionality
The `data-paths` config has been renamed to `seed-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
Could not read dbt run_results artifact
12:39:41  Partial parse save file not found. Starting full parse.
12:39:42  Found 6 models, 0 tests, 0 snapshots, 0 analyses, 168 macros, 0 operations, 0 seed files, …
```
=> feat: allow selection of non-existent nodes

.github/workflows/integration_tests.yml, .github/workflows/pytest.yml, .github/workflows/test_profiles.yml
Should we add `0.X` versions?
https://docs.getdbt.com/docs/core-versions#future-versions
<details>
closes FEA-247
</details>
=> tests: Test several dbt versions on integration tests

src/fal/planner/executor.py, src/fal/planner/schedule.py, src/fal/planner/tasks.py, tests/planner/test_schedule.py
We used to show the `failed nodes: ...` message even if everything succeeded, so this is fixed. Also refactors the node status handling.
=> refactor: scheduler node statuses, only show failed/skipped nodes

.github/workflows/integration_tests.yml, integration_tests/features/flow_run.feature, integration_tests/features/python_nodes.feature, integration_tests/features/steps/fal_steps.py, src/fal/cli/flow_runner.py
We also temporarily add support for before/after scripts (details TBD).
=> tests: add a CI run for fal flow run with experimental threads

.github/workflows/test_profiles.yml
We had too many tests scheduled: 4 Python versions and 4 dbt versions = 16 per adapter. So they were canceled because of time limits.
This brings them to 8 per adapter when scheduled and 4 per adapter for pull requests.
We can still improve by making each python version have a different schema to run adapter tests in parallel (the ones with remote data warehouse)
=> tests: Reduce dbt versions to test on schedule and fix matrix option

integration_tests/projects/008_pure_python_models/dbt_project.yml, integration_tests/projects/008_pure_python_models/models/fal/model_e.sql, integration_tests/projects/008_pure_python_models/models/fal/staging/model_c.sql, src/fal/cli/model_generator/model_generator.py
related to #441
In the target dir, it went from: `SELECT * FROM SELECT * FROM dbt_fal.fal_008_model_c` to `SELECT * FROM "test"."dbt_fal_custom"."fal_008_model_c"`.
Now dbt takes care of quoting and everything.
<details>
closes FEA-250
</details>
=> fix: reference {{ this }} for ephemeral models to get correct schema and table every time

src/fal/planner/executor.py
Example
```
integration_tests/projects/003_runtime_errors failed-skipped-messaging* ≡
❯ fal flow run
File 'fal/runtime_error_model.sql' was generated from 'runtime_error_model.py'.
Please do not modify it directly. We recommend committing it to your repository.
14:08:38  [WARNING]: Deprecated functionality
The `source-paths` config has been renamed to `model-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
14:08:38  [WARNING]: Deprecated functionality
The `data-paths` config has been renamed to `seed-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
14:08:38  Unable to do partial parsing because profile has changed
14:08:38  Unable to do partial parsing because a project dependency has been added
14:08:39  Found 3 models, …
```
=> feat: include before/after scripts in nodes failed/skipped report

src/fal/cli/cli.py, src/fal/cli/flow_runner.py, src/fal/planner/executor.py
Like dbt:
```
integration_tests/projects/003_runtime_errors main ≡
❯ dbt run
19:44:05  [WARNING]: Deprecated functionality
The `source-paths` config has been renamed to `model-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
19:44:05  [WARNING]: Deprecated functionality
The `data-paths` config has been renamed to `seed-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
19:44:05  Running with dbt=1.1.1
19:44:05  Found 3 models, 0 tests, 0 snapshots, 0 analyses, 168 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
19:44:05
19:44:05  Concurrency: 4 threads (target='dev')
19:44:05
19:44:05  1 of 2 START table model dbt_fal.fal_003_some_model ............................ [RUN]
19:44:05  2 of 2 START table …
```
=> fix: make exit code of Python non-zero if there are errors

src/fal/cli/flow_runner.py, src/fal/planner/schedule.py, src/fal/planner/tasks.py, src/fal/utils.py, tests/planner/test_tasks.py
Implements the `fal_results.json`. It is basically a mirror of the original DBT run results, but contains additional information for `post-hook`s and Python model scripts (including execution time, their name, executed thread, etc.).
=> feat: implement fal_results.json

integration_tests/features/structured_hooks.feature, integration_tests/projects/013_structured_hooks/fal_project.yml, integration_tests/projects/013_structured_hooks/models/model_b.sql, integration_tests/projects/013_structured_hooks/models/schema.yml, integration_tests/projects/013_structured_hooks/scripts/check_imports.py, integration_tests/projects/013_structured_hooks/scripts/funny_hook.py, integration_tests/projects/013_structured_hooks/scripts/local_hook.py, poetry.lock, pyproject.toml, src/fal/cli/cli.py, src/fal/fal_script.py, src/fal/packages/__init__.py, src/fal/packages/_run_hook.py, src/fal/packages/environment.py, src/fal/planner/schedule.py, src/fal/planner/tasks.py, src/faldbt/parse.py, src/faldbt/project.py
This PR implements "isolated hooks" (e.g., hooks which run in a different environment than the fal itself). Current implementation:
- Only uses virtual envs, so only requirements that can be installed with pip is available
- Virtual envs that are created for an environment set is cached. So in the second run for the same hook (or a different hook that has the same exact dependencies) it will be very fast.
- Each environment contains `fal` + `dbt-core` and all the dbt adapters you have locally (we scan all the installed python packages you have, and install the same version of every `dbt-*` adapter)
```yaml
- name: model_b
meta:
fal:
pre-hook:
- path: local_hook.py
- path: funny_hook.py
environment: funny
- path: check_imports.py
environment: not-funny
with:
import: pyjokes …
```
=> feat: implement isolated hooks

.github/actions/setup-local-fal/action.yml, poetry.lock, pyproject.toml, src/faldbt/lib.py
Now users would need to run `pip install fal[<adapter>]` to get any extra dependencies needed for their adapter of choice.
```sh
$ pip install fal[snowflake]
```
```sh
$ pip install fal[bigquery]
```
<details>
<summary>Adapters to test</summary>
- bigquery
- snowflake
- postgres
- redshift
- duckdb
</details>
=> chore: separate adapters dependencies as extras

.github/workflows/generate_typing.yml, src/fal/typing.py, tools/generate_typing_context.py
Problem: https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs
> Commits made by this Action do not trigger new Workflow runs
> 
> The resulting commit will not trigger another GitHub Actions Workflow run. This is due to [limitations set by GitHub](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow).
> 
>     When you use the repository's GITHUB_TOKEN to perform tasks on behalf of the GitHub Actions app, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs.
> 
> You can change this by creating a new [Personal Access Token (PAT)](https://github.com/settings/tokens/new), …
=> ci: Add GitHub action that generates typing and commits it

integration_tests/features/structured_hooks.feature, integration_tests/projects/013_structured_hooks/fal_project.yml, integration_tests/projects/013_structured_hooks/models/fal/model_d.sql, integration_tests/projects/013_structured_hooks/models/fal/model_e.sql, integration_tests/projects/013_structured_hooks/models/model_c.sql, integration_tests/projects/013_structured_hooks/models/model_d.py, integration_tests/projects/013_structured_hooks/models/model_e.py, integration_tests/projects/013_structured_hooks/models/schema.yml, integration_tests/projects/013_structured_hooks/scripts/joke_version.py, src/fal/fal_script.py, src/fal/node_graph.py, src/fal/packages/_run_hook.py, src/fal/packages/environment.py, src/fal/planner/executor.py, src/fal/planner/schedule.py, src/fal/planner/tasks.py, src/faldbt/project.py, tests/planner/test_schedule.py, tests/planner/test_tasks.py, tests/planner/utils.py
Requires #489, this PR implements support for isolation in the scope of individual models. Each model can now define an `environment:` setting directly under `fal:` block, and that setting will be applied to both Python model itself (if there is any) and all the hooks below it (unless they manually override).
=> feat: model-scoped environments

integration_tests/projects/000_fal_run/fal_scripts/write_to_model.py, src/fal/planner/tasks.py
Seems like this went unnoticed because we can't create empty models locally when we were trying to run the test `features/run.feature:128`. Should be fixed now.
=> fix: correctly serialize script type when constructing task

.github/workflows/generate_typing.yml
It seems like the PRs coming from my fork fail at this stage, it is not big since we don't receive much outside contributions but just to make the CI green I think we can ignore this job on forks.
=> ci: only run generate typing job when originating from upstream

.github/actions/setup-local-fal/action.yml, .github/workflows/python-release.yml
Getting this in GH Actions:
```
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.8.13/x64/bin/poetry", line 5, in <module>
from poetry.console import main
File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/poetry/console/__init__.py", line 1, in <module>
from .application import Application
File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/poetry/console/application.py", line 7, in <module>
from .commands.about import AboutCommand
File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/poetry/console/commands/__init__.py", line 2, in <module>
from .add import AddCommand
File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/poetry/console/commands/add.py", line 8, in <module>
from .init …
```
=> ci: Fix poetry installation in GH actions

integration_tests/features/context_info.feature, integration_tests/projects/005_functions_and_variables/fal_scripts/context.py, src/fal/fal_script.py
resolves #535 
Now available in the context:
```py
extra = f"target name: {context.target.name}\n"
extra += f"target profile: {context.target.profile_name}\n"
extra += f"target database: {context.target.database}\n"
```
class:
```py
@dataclass
class ContextTarget:
def __init__(self, config: RuntimeConfig):
self.profile_name = config.profile_name
self.name = config.target_name
self.threads = config.threads
self.type = config.credentials.type
self.database = config.credentials.database
self.schema = config.credentials.schema
```
- postgres
- 3.7
- 3.8
- 3.10
=>  feat: Add target to context object in fal scripts

src/fal/packages/dependency_analysis.py, src/fal/packages/environments/virtual_env.py, src/fal/packages/isolated_runner.py
This introduces an option to allow Fal use your local Python as the primary environment. With this, if you have dbt-core installed from a local repository (or actually any python package), we can use them on the isolated environments.
```
environments:
- name: not-funny
type: venv
_inherit_from_local: true
- name: funny
type: venv
requirements:
- pyjokes==0.5.0
_inherit_from_local: true
```
Currently a private option.
=> feat: make fal work with local dev envs

adapter/src/dbt/adapters/fal/connections.py
now this works:
```
duckdb:
type: duckdb
path: "/Users/<user>/duck_db_dbt_dump.db" 
python_adapter:
type: fal
````
no more `database: None` or `schema: None`
<details>
closes fea-426
</details>
=> make database and schema no longer needed in credentials config

.github/workflows/test_profiles.yml, src/fal/cli/fal_runner.py
We were getting 
```
ImportError: cannot import name 'DEFAULT_PROFILES_DIR' from 'dbt.config.profile' (/Users/omer/fal-dev/dbt_snowflake_env/lib/python3.8/site-packages/dbt/config/profile.py)
```
For 1.3 candidate releases.
closes FEA-423
- postgres
- snowflake
- bigquery
- duckdb
- 3.8
=> fix: adapt profiles_dir info import for new location in dbt 1.3

poetry.lock, pyproject.toml
Make the minimum Python 3.7.2 like dbt:
https://github.com/dbt-labs/dbt-core/blob/dc96352493098ca5306e104a03ce5333f670f697/core/setup.py#L5-L8
- postgres
- snowflake
- bigquery
- 3.8
- 3.7
- 3.9
- 3.10
=> chore: Make minimum Python 3.7.2 like dbt

integration_tests/features/globals.feature, integration_tests/features/run.feature, src/fal/cli/args.py, src/fal/cli/fal_runner.py, src/fal/telemetry/telemetry.py, tests/test_telemetry.py
Add `--globals` flag for more explicit global script execution. With this change, if any model selector flag OR a `--scripts` flag are passed, global scripts are NOT executed by default. In order to run them in these scenarios, users need to pass the `--globals` flag.
Following scenarios are now tested in integrations tests:
- fal runs globals by default when no model or script selection is indicated
- fal run doesn't trigger globals with select flag
- fal run triggers global scripts with model select and `--globals` flags
- script selection with `--scripts` flag doesn't run global scripts
- global scripts are run when both `--scripts` and `--globals` flags are passed
- postgres
- 3.8
=> feat: add --globals flag for more explicit global script execution

.github/workflows/test_profiles.yml, src/fal/cli/cli.py, src/fal/cli/dbt_runner.py, src/fal/cli/model_generator/model_generator.py, src/fal/el/airbyte.py, src/fal/el/fivetran.py, src/fal/fal_script.py, src/fal/packages/environments/base.py, src/fal/packages/isolated_runner.py, src/fal/planner/executor.py, src/fal/planner/plan.py, src/fal/planner/tasks.py, src/fal/utils.py, src/faldbt/lib.py, src/faldbt/logger.py, src/faldbt/parse.py, src/faldbt/project.py, src/faldbt/version.py
```
❯ python
Python 3.8.13 (default, Sep 30 2022, 17:13:29)
[Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import faldbt.lib
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/matteo/Projects/fal-ai/fal/src/faldbt/lib.py", line 15, in <module>
from fal.logger import LOGGER
File "/Users/matteo/Projects/fal-ai/fal/src/fal/__init__.py", line 3, in <module>
from faldbt.project import (
File "/Users/matteo/Projects/fal-ai/fal/src/faldbt/project.py", line 41, in <module>
from fal.logger import LOGGER
File "/Users/matteo/Projects/fal-ai/fal/src/fal/logger.py", line 52, in <module>
if lib.version_compare("1.1.0") < 0:
AttributeError: partially initialized module 'faldbt.lib' has no …
```
=> chore: Make importing faldbt.lib not have circular dependencies

adapter/src/dbt/adapters/fal/teleport_support/duckdb.py
From https://github.com/jwills/dbt-duckdb#configuring-your-profile
> As of version 1.2.0, dbt-duckdb also allows you to configure your S3 settings in your credentials, including s3_region and either s3_session_token or s3_access_key_id and s3_secret_access_key, so that you can use dbt-duckdb to read and transform data stored in S3 files. You can also specify an arbitrary number of [DuckDB extensions](https://duckdb.org/docs/extensions/overview) to load as part of your dbt-duckdb project using the extensions: [] credentials field.
=> fix: stop overwriting dbt-duckdb s3 settings

adapter/src/dbt/adapters/fal/impl.py, adapter/src/dbt/adapters/fal/teleport_adapter_support.py, adapter/src/dbt/adapters/fal/teleport_support/duckdb.py, adapter/src/dbt/include/fal/macros/teleport_duckdb.sql
Teleport + S3 + DuckDB
Example profiles.yml:
```
jaffle_shop:
target: dev_with_fal
outputs:
dev_with_fal:
type: duckdb
path: "duck_db_dbt_dump.db"
python_adapter:
type: fal
teleport:
type: s3
s3_bucket: fal-dbt-test
s3_region: my_region
s3_access_key_id: my_key_id
s3_access_key: my_key
```
=> feat: Make teleport work with s3 and duckdb

pyproject.toml
=> Restrict dill version 0.3.6< since it is breaking fal

adapter/integration_tests/projects/simple_project/models/model_c.py, adapter/src/dbt/adapters/fal/wrappers.py, adapter/src/dbt/include/fal/macros/materializations/table.sql
With this change now Python models with encapsulating adapter can have 
```py
def model(dbt, fal):
dbt.config(materialized='table')
```
and it will run on fal.
❗ ❗❗ This makes it impossible to run some Python models on fal and others on the db-adapter's Python runtime. All models will run with fal.
- postgres
- snowflake
- bigquery
- duckdb
- 3.8
=> feat: make encapsulate pass-through sql tables

.github/workflows/python-release.yml
Example skipped because it did not run from the `release` branch: https://github.com/fal-ai/fal/actions/runs/3372641323
Example running becase the checkbox was checked (cancelled manually): https://github.com/fal-ai/fal/actions/runs/3372658764/jobs/5596344586
=> chore: Remove automatic release and check branch of release

adapter/integration_tests/projects/simple_project/dbt_project.yml, adapter/src/dbt/adapters/fal/impl.py
We no longer have to specify the wrapped adapter's quoting behavior in dbt_project.yml
=> fix(dbt-fal): Find wrapped adapter Relation class on init 

adapter/src/dbt/adapters/fal_experimental/impl.py
Now when a `ctrl-c` happens, it cancels or not depending on the wrapped db adapter config.
We may need to work on handling cancels better in the future. But it's OK for now.
=> fix(dbt-fal): Inherit is_cancelable from the wrapped adapter

adapter/src/dbt/adapters/fal/wrappers.py, adapter/src/dbt/adapters/fal_experimental/adapter.py
Setting `self._parse_replacements_` which was not being set and is built in the `AdapterMeta` class.
I will try to explain what was going on:
1. compiling was loading the manifest
2. which was parsing the project and all it's dependencies
3. the fivetran package had some database-specific jinja
4. which failed static jinja parsing and triggered an [adapter-connected parse](https://github.com/dbt-labs/dbt-core/blob/930bd3541e19f160ed79f3cc6c26ea7085ced760/core/dbt/parser/models.py#L337-L338)
```py
super().render_update(node, config)
fire_event(StaticParserFallbackJinjaRendering(path=node.path))
```
5. then in the fivetran package jinja we get [an `adapter.get_columns_in_relation(...)` call](https://github.com/fivetran/dbt_stripe_source/blob/3a51c3f2097597be7b838081a367bcf77d900912/models/st …
=> fix(dbt-fal): Include _parse_replacements_ from DB adapter into wrapper adpater

adapter/integration_tests/projects/env_project/dbt_project.yml, adapter/integration_tests/projects/simple_project/dbt_project.yml, adapter/integration_tests/projects/simple_project/models/model_c.py, adapter/src/dbt/adapters/fal_experimental/utils/__init__.py
This is done for consistency with fal. There might be future use cases where scripts path cannot be the dbt project path, so we have to be mindful of that.
=> chore(dbt-fal): change default script path to project dir

adapter/src/dbt/adapters/fal_experimental/support/trino.py
The user is now able to install dbt-fal[trino] and run it even if the older version of dbt-trino is installed.
=> fix(dbt-fal): trino none credential handling

.github/workflows/test_integration_cli.yml
- postgres
- snowflake
- bigquery
- redshift
- duckdb
- athena
- 3.8
- 3.7
- 3.9
- 3.10
=> tests: use latest 1.3 version for integration tests

src/faldbt/parse.py
Since in dbt project people can use a variety of .yaml, and .yml files, I added the support for scanning .yaml files
GitHub: resolves #684
=> Add support for .yaml files in fal dbt parser

.github/workflows/test_cli.yml, .github/workflows/test_integration_adapter.yml, .github/workflows/test_integration_cli.yml, adapter/integration_tests/features/sql_model.feature, adapter/integration_tests/features/steps/fal_adapter_steps.py, adapter/integration_tests/projects/simple_project/models/model_a.sql, adapter/src/dbt/adapters/fal/wrappers.py
In SQL context we should get the `adapter.type()` to be the encapsulated adpter type, since they process the SQL.
And in all contexts, the target (and env) are the encapsulated adapter type, because they always offer the storage (for Python too).
- postgres
- snowflake
- bigquery
- redshift
- duckdb
- athena
- 3.8
=> feat: get datawarehouse type in SQL context

adapter/src/dbt/adapters/fal_experimental/telemetry/telemetry.py, src/fal/telemetry/telemetry.py
`DO_NOT_TRACK="0"` was enabling tracking by mistake.
https://consoledonottrack.com/
> Authors, do the ethical thing and respect the following environment variable in your software and your limited rights to the computers of your users:
> ```
> export DO_NOT_TRACK=1
> ```
=> fix: make DO_NOT_TRACK behave as specified

.github/workflows/python-release.yml
I have not checked where it comes from. Quick hack.
=> fix: delete automatically added git submodule when releasing

.github/workflows/test_integration_adapter.yml, adapter/integration_tests/features/cloud.feature, adapter/integration_tests/features/teleport.feature, adapter/integration_tests/profiles/bigquery/profiles.yml, adapter/integration_tests/profiles/duckdb/profiles.yml, adapter/integration_tests/profiles/postgres/profiles.yml, adapter/integration_tests/profiles/redshift/profiles.yml, adapter/integration_tests/profiles/snowflake/profiles.yml, adapter/integration_tests/profiles/trino/profiles.yml, adapter/poetry.lock, adapter/pyproject.toml, adapter/src/dbt/adapters/fal/connections.py, adapter/src/dbt/adapters/fal_experimental/adapter.py, adapter/src/dbt/adapters/fal_experimental/connections.py, adapter/src/dbt/adapters/fal_experimental/impl.py, adapter/src/dbt/adapters/fal_experimental/utils/environments.py
in `profiles.yml` you can now pass some credentials:
```
my_profile:
target: fal_cloud
outputs:
fal_cloud:
type: fal
db_profile: db
host: my_host
secret: my_secret
secret_id: my_secret_id
db:
type: postgres
...
```
And now, all Python models will run on isolate cloud by default. 
You can specify environments in `fal_project.yml`:
```
environments:
- name: funny-cloud
type: venv
requirements:
- pyjokes==0.6.0
```
You can specify machine sizes in model configs:
```
def model(dbt, fal):
dbt.config(materialized="table")
dbt.config(fal_machine="GPU") # "S" by default
...
```
If you want to run fal locally, you should omit credentials from `profiles.yml`:
```
my_profile:
target: fal_local
outputs:
fal_local:
type: fal
db_profile: db
db:
type: postgres
...
```
=> feat(dbt-fal): enable fal cloud

adapter/src/dbt/adapters/fal/connections.py, adapter/src/dbt/adapters/fal/impl.py, adapter/src/dbt/adapters/fal_experimental/connections.py
- When passing `--threads 1` flag, it was being ignored and using the wrapped db adapter.
- When setting `threads: 1` in the profile config, it was being ignored and using the wrapped db adapter.
=> fix(dbt-fal): only inherit threads from db profile when is not set in flag or profile config

adapter/poetry.lock, adapter/pyproject.toml
I think we are good
1. postgres has a failure for fal-dependent test only (we have not made fal dbt-core==1.4 compatible)
2. there is no dbt-duckdb==1.4 published
=> fix(dbt-fal): Install compatible dependencies for bigquery and snowflake

.github/workflows/test_integration_cli.yml, adapter/src/dbt/adapters/fal/wrappers.py, adapter/src/dbt/adapters/fal_experimental/impl.py, adapter/src/dbt/adapters/fal_experimental/utils/environments.py
FYI: the quoting was fixed in dbt for 1.4+ in https://github.com/dbt-labs/dbt-core/pull/6620
=> refactor: move some hacks location

.github/workflows/test_integration_cli.yml, adapter/integration_tests/profiles/athena/profiles.yml, adapter/src/dbt/adapters/fal/wrappers.py, adapter/src/dbt/adapters/fal_experimental/adapter_support.py, adapter/src/dbt/adapters/fal_experimental/impl.py, adapter/src/dbt/adapters/fal_experimental/support/athena.py, adapter/src/dbt/adapters/fal_experimental/utils/environments.py
dbt-athena from PyPI doesn't support dbt 1.3, but [dbt-athena-community](https://github.com/dbt-athena/dbt-athena) does
dbt-athena-community does not support dbt 1.4, so this branch doesn't need to be merged to `main`. Instead, we will release a patch to dbt-fal 1.3 in order to add support to dbt-athena-community.
Once either of these add support for dbt 1.4, we can create a new PR that incorporates those changes.
=> feat(dbt-adapter): dbt-athena-community support

projects/adapter/src/dbt/adapters/fal_experimental/telemetry/telemetry.py, projects/fal/src/fal/telemetry/telemetry.py, projects/fal/tests/test_telemetry.py
Adds a new property to telemetry, the `adapter_type`.
After a bit of trial and error, it seems like the correct (i.e. runtime resolved) field comes from `config.to_target_dict()["type"]`. The more obvious `config.get_metadata().adapter_type` returns the static value from the configuration.
---
**Note:** this PR replaces https://github.com/fal-ai/fal/pull/737
=> feat: add adapter_type to telemetry

projects/fal/src/fal/cli/args.py
=> fix: Remove forgotten deprecated options

projects/fal/integration_tests/projects/000_fal_run/dbt_project.yml, projects/fal/integration_tests/projects/001_flow_run_with_selectors/dbt_project.yml, projects/fal/integration_tests/projects/002_jaffle_shop/dbt_project.yml, projects/fal/integration_tests/projects/003_runtime_errors/dbt_project.yml, projects/fal/integration_tests/projects/004_globals/dbt_project.yml, projects/fal/integration_tests/projects/005_functions_and_variables/dbt_project.yml, projects/fal/integration_tests/projects/006_script_paths/dbt_project.yml, projects/fal/integration_tests/projects/007_ipynb_scripts/dbt_project.yml, projects/fal/integration_tests/projects/008_pure_python_models/dbt_project.yml, projects/fal/integration_tests/projects/009_execute_sql_function/dbt_project.yml, projects/fal/integration_tests/projects/010_source_freshness/dbt_project.yml, projects/fal/integration_tests/projects/011_highly_parallelizable/dbt_project.yml, projects/fal/integration_tests/projects/012_model_generation_error/dbt_project.yml, projects/fal/integration_tests/projects/013_structured_hooks/dbt_project.yml, projects/fal/integration_tests/projects/014_broken_dbt_models/dbt_project.yml, projects/fal/tests/mock/dbt_project.yml
This format was [introduced in 1.0](https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.0#renamed-fields-in-dbt_projectyml) and since we no longer support <1.0, we can update for the new format.
=> chore: Update dbt_project.yml format

.github/workflows/test_integration_adapter.yml, projects/adapter/integration_tests/features/source.feature, projects/adapter/integration_tests/features/sql_model.feature, projects/adapter/src/dbt/adapters/fal_experimental/support/trino.py, projects/adapter/src/dbt/adapters/fal_experimental/utils/environments.py
=> fix(dbt-fal): support latest dbt-trino

projects/adapter/src/dbt/adapters/fal_experimental/adapter_support.py, projects/adapter/src/dbt/adapters/fal_experimental/support/postgres.py
dbt-fal currently [uses a generic pandas.DataFrame.to_sql call](https://github.com/fal-ai/fal/blob/070592fc0d24d6093c97fe70a9f7cfb8a1da71ec/projects/adapter/src/dbt/adapters/fal_experimental/adapter_support.py#L97-L103) when using adapters others than `snowflake`, `bigquery`, and `duckdb`. This results in an `INSERT` statement per row when writing dataframes to PostgreSQL, which is excruciatingly slow.
The `pandas.DataFrame.to_sql` can take an optional `method` argument that controls the SQL insertion clause. In particular, the Pandas user guide [provides an example for PostgreSQL that uses `COPY FROM`](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-sql-method) to efficiently insert rows.
Here are some numbers from a Python model that I'm working on. The model reads …
=> Improve speed of inserts on PostgreSQL

projects/adapter/README.md, projects/fal/README.md
It just renders it: https://pypi.org/project/dbt-fal/1.4.1/
=> docs: remove base HTML tag from readme

projects/adapter/integration_tests/projects/source_freshness/models/schema.yml, projects/adapter/src/dbt/adapters/fal/impl.py, projects/adapter/src/dbt/adapters/fal/wrappers.py, projects/adapter/src/dbt/adapters/fal_experimental/adapter_support.py
We are seeing 
> Error: 00:24:01.472113 [error] [MainThread]: Table “freshness_table” not found
This was introduced in https://github.com/dbt-labs/dbt-core/issues/7114
```py
def source(*args, dbt_load_df_function):
sources = {"freshness_test.freshness_table": "test.dbt_fal_custom.freshness_table"}
key = ".".join(args)
return dbt_load_df_function(sources[key])
```
vs
```py
def source(*args, dbt_load_df_function):
sources = {"freshness_test.freshness_table": "\"test\".\"dbt_fal_custom\".\"freshness_table\""}
key = '.'.join(args)
return dbt_load_df_function(sources[key])
```
Notice the quotes in the `sources` dict.
- postgres
- 3.8
=> fix: handle new relation quoting for Python introduced in dbt-1.4.5

projects/adapter/src/dbt/adapters/fal/wrappers.py
looks like
```
{ ..., 'fal_host': 'api.alpha.fal.ai'}
```
=> chore: differentiate cloud from non-cloud users

projects/fal/src/faldbt/project.py
=> fix: column_name resolution when parsing dbt generic tests

projects/fal/integration_tests/features/flow_run.feature, projects/fal/integration_tests/projects/001_flow_run_with_selectors/models/schema.yml, projects/fal/src/fal/cli/selectors.py
Fixes `flow run --select tag:my_tag` selection to select all relevant models.
Closes: #807
=> fix: flow run tag selection

projects/adapter/poetry.lock, projects/adapter/pyproject.toml
dbt-snowflake changed their dependency of the snowflake conector to 3.0 (https://github.com/dbt-labs/dbt-snowflake/commit/967a8e93b7e60a0442cc9f34b3b2172ecc085d5b)
GitHub: resolves #834 
- snowflake
=> fix: upgrade snowflake-connector-python version for dbt-snowflake 1.4.2

.github/workflows/test_integration_adapter.yml, projects/adapter/integration_tests/features/steps/fal_adapter_steps.py, projects/adapter/integration_tests/projects/env_project/dbt_project.yml, projects/adapter/integration_tests/projects/simple_project/dbt_project.yml, projects/adapter/integration_tests/projects/source_freshness/dbt_project.yml, projects/adapter/poetry.lock, projects/adapter/pyproject.toml, projects/adapter/src/dbt/adapters/fal/impl.py, projects/adapter/src/dbt/adapters/fal/load_db_profile.py, projects/adapter/src/dbt/adapters/fal_experimental/adapter.py, projects/adapter/src/dbt/adapters/fal_experimental/adapter_support.py, projects/adapter/src/dbt/adapters/fal_experimental/impl.py, projects/adapter/src/dbt/adapters/fal_experimental/teleport.py, projects/adapter/src/dbt/adapters/fal_experimental/teleport_support/snowflake.py, projects/adapter/src/dbt/include/fal/macros/materializations/table.sql, projects/adapter/src/dbt/include/fal_experimental/macros/materializations/table.sql
Refactor and adapt DB profile loading for dbt-fal.
It mostly follows the same ideas adapted to some changes on how flags are loaded and avoiding a new parser for some checks.
In general this is a better implementation than before but does not really take advantage of any new API introduced in 1.5
Other good thing with this change is that now running `dbt run` on the integration test projects does not need a `temp_dir` env var being set, becuase it handles it exclusively for behave.
Got it to just fail for `features/source.feature:9  Run a Python model that queries a source in local environment`.
That failure would be related to fal-cli tool, because we fill the source with a `FalDbt` instance.
```
❯ python load_freshness_table.py . ~/.dbt/
Traceback (most recent call last):
File …
```
=> feat(dbt-fal): adapt to new 1.5 dbt changes

projects/adapter/pyproject.toml, projects/adapter/src/dbt/adapters/fal_experimental/support/redshift.py
As mentioned in https://discord.com/channels/908693336280432750/940966301680156683/941335732923007056
The default value for varchar in dbt-fal is 256, which is too small for many applications. This changes the default to max so that most of models work without problem.
=> Change default varchar size in redshift to 65535

.github/workflows/test_integration_adapter.yml, .github/workflows/test_integration_cli.yml
=> chore: remove aws tests
